### ISSUE TITLE
NAOqui 2.1.4 OS does not stand on startup with latest naoqi_dcm_driver

### ISSUE THREAD

**Issue by dcconner** [ros-naoqi/naoqi_dcm_driver#5]
The latest naoqi_dcm_driver builds with the noaqi_libqi and _libqicore version 2.5  according to the CMake build options.

If we try to run this with our existing Nao robots with NAOqi OS 2.1.4, the robot fails to stand on startup.
On a Nao with version with NAOqi OS 2.1.2 the robot stands as expected.

Should we be using the libqi   version 2.5 with the on robot software 2.1.4?
Should we revert back to using the 2.1.4 SDK, or is there a secret 2.5 version for the Nao robot?

**Comment by nlyubova** [comment]
naoqi-libqi and the latest available Naoqi 2.xxx version for Nao should work fine together.

What the robot does when you try to stand up?

Did you try just to move arms via ROS naoqi_dcm_driver ? You can also try to move it’s head. The idea is to start with simple movements  first and then go to stand up. Also, there is a config file https://github.com/ros-naoqi/nao_dcm_robot/blob/master/nao_dcm_bringup/config/nao_dcm.yaml
where you can change ControllerFrequency that can help to solve the problem.

By the way, how did you install it? From source?  Did you follow https://github.com/ros-naoqi/nao_dcm_robot/blob/master/README.md ?

**Comment by dcconner** [comment]
We were trying to run standard apt-get install for ros-kinetic, and then also build from source.   
We were seeing some oddities with 2.1.4 OS.
Those were related to early testing, and then a different startup behavior between 2.1.2 and 2.1.4.

I was concerned by the large difference in version numbers, and wanted to make sure that we were being consistent with intended use before we sunk too much time into trying to get it working.   Thanks for your encouragement that they should be consistent; we will working on our new development with this version and our Nao software.   

I will leave this open a bit longer, and then close once I verify during testing.

**Comment by nlyubova** [comment]
Regarding the last version of Image for Nao please ask on the official SoftBank/Aldebaran forum since this question is not related to this open-source

**Comment by dcconner** [comment]
Confirmed latest kinetic "2.5" library  running with NAO robot OS 2.1.4.
